<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>mini_caml_fsharp</RootNamespace>

    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ParserCombinators.fs" />
    <Compile Include="SExpr.fs" />
    <Compile Include="Type.fs" />
    <Compile Include="Id.fs" />
    <Compile Include="M.fs" />
    <Compile Include="S.fs" />
    <Compile Include="Syntax.fs" />
    <Compile Include="Parsing.fs" />
    <Compile Include="ParsingTests.fs" />
    <Compile Include="Typing.fs" />
    <Compile Include="UnificationTests.fs" />
    <Compile Include="TypingTests.fs" />
    <Compile Include="KNorm.fs" />
    <Compile Include="KNormalisation.fs" />
    <Compile Include="KNormalisationTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
        <PackageReference Include="NUnit" Version="3.14.0" />
        <PackageReference Include="NUnit.Analyzers" Version="3.9.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    </ItemGroup>

</Project>
